# run: conda env create -f environment.yml
name: pixelnerf
channels:
  - pytorch
  - defaults
dependencies:
  - python>=3.8
  - pip
  - pip:
      - pyhocon==0.3.6
      - pyparsing==2.3.1
      - opencv-python
      - dotmap
      - tensorboard
      - imageio
      - imageio-ffmpeg
      - ipdb
      - pretrainedmodels
      - lpips
  - scipy
  - numpy
  - matplotlib
  - pytorch==1.8.0
  - torchvision==0.9.0
  - scikit-image==0.17.2
  - tqdm
